version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage

  mcp:
    build:
      context: ./mcp
      dockerfile: Dockerfile
    container_name: mcp_sever
    ports:
      - "5000:8000"
      - "8501:8501"
    volumes:
      - ./mcp:/app
    command: bash -c "python sever.py & streamlit run DocumentManager.py && wait"